"""initial schema

Revision ID: 7f6ed0e8d2c9
Revises: 
Create Date: 2026-07-07 10:32:36.954960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f6ed0e8d2c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tenant_code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('discipline_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rule_code', name='uq_discipline_rules_user_rule')
    )
    op.create_table('discipline_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('score_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trades_analyzed', sa.Integer(), nullable=False),
    sa.Column('violations_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_disciplined_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'score_date', name='uq_discipline_scores_user_date')
    )
    op.create_table('discipline_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('attempted_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('was_blocked', sa.Boolean(), nullable=False),
    sa.Column('session_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_violations_user_date', 'discipline_violations', ['user_id', 'session_date'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.create_table('trading_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_cooldown_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('last_sl_hit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', name='uq_trading_sessions_user_date')
    )
    op.create_table('virtual_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('consecutive_disciplined_trades', sa.Integer(), nullable=False),
    sa.Column('discipline_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tier IN ('TIER_1', 'TIER_2', 'TIER_3')", name='ck_virtual_accounts_valid_tier'),
    sa.CheckConstraint('balance >= 0', name='ck_virtual_accounts_balance_non_negative'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_virtual_accounts_user_id')
    )
    op.create_index('idx_virtual_accounts_tenant_id', 'virtual_accounts', ['tenant_id'], unique=False)
    op.create_table('virtual_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('entry_ltp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('brokerage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('slippage_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('setup_tag', sa.String(length=30), nullable=False),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('is_discipline_compliant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('BUY', 'SELL')", name='ck_virtual_orders_action'),
    sa.CheckConstraint("option_type IN ('CE', 'PE')", name='ck_virtual_orders_option_type'),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED', 'CANCELLED', 'SL_HIT', 'TARGET_HIT')", name='ck_virtual_orders_status'),
    sa.CheckConstraint('quantity > 0', name='ck_virtual_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['virtual_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_virtual_orders_status', 'virtual_orders', ['status'], unique=False)
    op.create_index('idx_virtual_orders_tenant_id', 'virtual_orders', ['tenant_id'], unique=False)
    op.create_index('idx_virtual_orders_user_id', 'virtual_orders', ['user_id'], unique=False)
    op.create_index('idx_virtual_orders_user_status', 'virtual_orders', ['user_id', 'status'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('brokerage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('setup_tag', sa.String(length=30), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('is_discipline_compliant', sa.Boolean(), nullable=False),
    sa.Column('violations_attempted', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('emotion_tag', sa.String(length=20), nullable=True),
    sa.Column('mistake_category', sa.String(length=30), nullable=True),
    sa.Column('pre_trade_thesis', sa.Text(), nullable=True),
    sa.Column('post_trade_review', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['virtual_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_journal_entries_order_id')
    )
    op.create_index('idx_journal_entries_tenant_id', 'journal_entries', ['tenant_id'], unique=False)
    op.create_index('idx_journal_entries_user_date', 'journal_entries', ['user_id', 'trade_date'], unique=False)
    op.create_table('virtual_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_ltp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margin_blocked', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['virtual_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['virtual_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_virtual_positions_order_id')
    )
    op.create_index('idx_virtual_positions_tenant_id', 'virtual_positions', ['tenant_id'], unique=False)
    op.create_index('idx_virtual_positions_user_open', 'virtual_positions', ['user_id', 'is_open'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_virtual_positions_user_open', table_name='virtual_positions')
    op.drop_index('idx_virtual_positions_tenant_id', table_name='virtual_positions')
    op.drop_table('virtual_positions')
    op.drop_index('idx_journal_entries_user_date', table_name='journal_entries')
    op.drop_index('idx_journal_entries_tenant_id', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('idx_virtual_orders_user_status', table_name='virtual_orders')
    op.drop_index('idx_virtual_orders_user_id', table_name='virtual_orders')
    op.drop_index('idx_virtual_orders_tenant_id', table_name='virtual_orders')
    op.drop_index('idx_virtual_orders_status', table_name='virtual_orders')
    op.drop_table('virtual_orders')
    op.drop_index('idx_virtual_accounts_tenant_id', table_name='virtual_accounts')
    op.drop_table('virtual_accounts')
    op.drop_table('trading_sessions')
    op.drop_index('idx_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_violations_user_date', table_name='discipline_violations')
    op.drop_table('discipline_violations')
    op.drop_table('discipline_scores')
    op.drop_table('discipline_rules')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
