"""what changed

Revision ID: 1674dd5f928c
Revises: 20260721_user_settings
Create Date: 2026-07-20 18:58:49.576363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1674dd5f928c'
down_revision: Union[str, None] = '20260721_user_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_users_tenant_email_lower', table_name='users')
    op.drop_index('idx_virtual_orders_strategy_id', table_name='virtual_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_virtual_orders_strategy_id', 'virtual_orders', ['strategy_id'], unique=False)
    op.create_index('ux_users_tenant_email_lower', 'users', ['tenant_id', sa.text('lower(email::text)')], unique=True)
    # ### end Alembic commands ###
